### ISSUE TITLE
Python Easy: Instruction Language

### ISSUE THREAD

**Issue by unfirthman** [nikohoffren/fork-commit-merge#853] opened 2023-10-03 16:12 UTC
Hello! I would like to propose an alteration to the instructions for the easy python task.

Currently it reads:

`# TODO: Create the Simple Python Program to Interact with Lists`

I propose:

`# TODO: Create a Simple Python Program that returns the sum of two numbers`

Happy to create a PR for this. I currently have a local branch with the suggested changes above.

**Comment by nikohoffren** [comment] 2023-10-03 16:24
> Hello! I would like to propose an alteration to the instructions for the easy python task.
> 
> Currently it reads:
> 
> `# TODO: Create the Simple Python Program to Interact with Lists`
> 
> I propose:
> 
> `# TODO: Create a Simple Python Program that returns the sum of two numbers`
> 
> Happy to create a PR for this. I currently have a local branch with the suggested changes above.

Hi! Do you mean that you want to create new Python easy level issue? The [current Python easy level issue](https://github.com/nikohoffren/fork-commit-merge/issues/447) is about creating a list of the first ten natural numbers and printing the sum of the numbers in the list to the console, it is not about returning a sum of two numbers.

**Comment by unfirthman** [comment] 2023-10-03 16:38
Ah, okay! I see now, thank you.

My suggestion, would be to change the language in `number_list.py` to more accurately reflect the language in the main issue. Something like:

`# TODO: Create a Simple Python Program that:
# lists the first 10 natural numbers
# prints that list to the console, and 
# prints the sum of the numbers of that list`

Or something along those lines. I realize now that I should be submitting my changes in reference to the related issue. If I had began by reading the instructions there, I wouldn't have been confused!

So, up to you if this is worth the space it takes. No worries if this just needs to be closed!

As for adding a new Python easy level issue, I would be happy to if that's something you would be interested in!

**Comment by nikohoffren** [comment] 2023-10-03 16:49
> Ah, okay! I see now, thank you.
> 
> My suggestion, would be to change the language in `number_list.py` to more accurately reflect the language in the main issue. Something like:
> 
> `# TODO: Create a Simple Python Program that:` `# lists the first 10 natural numbers` `# prints that list to the console, and ` `# prints the sum of the numbers of that list`
> 
> Or something along those lines. I realize now that I should be submitting my changes in reference to the related issue. If I had began by reading the instructions there, I wouldn't have been confused!
> 
> So, up to you if this is worth the space it takes. No worries if this just needs to be closed!
> 
> As for adding a new Python easy level issue, I would be happy to if that's something you would be interested in!

Sure! I think it would be a good idea to change the TODO instructions in the file to something like what you suggested. You can make a PR out of that and i get it merged.

New issues are always welcome! You can make a PR about the issue that you are thinking of. It can be Python Easy, Medium, Hard or maybe in some other language/framework too. All you would need to do is basically just add a new file for the issue inside of the easy, medium or hard folders with those TODO instructions about what the issue is and make a PR. I can then later on make a Issue out of that. You would also get your name as creator into the Issue description.

**Closed** 2023-10-05 05:33 UTC
